source ENV.fetch('GEM_SOURCE', 'https://rubygems.org')
ruby '2.2.1'

gem 'rails', '4.2.1'

# GitLab API
gem 'gitlab'

# database
gem 'pg'

# authentication/autorization
gem 'devise'
gem 'cancan'

# template
gem 'haml-rails'

# form
gem 'cocoon' # nested form using jquery

# centralized configuration
gem 'configatron', '2.13.0'

# turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'
gem 'jquery-turbolinks'

# build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'

# build REST APIs with ease. Read more: https://github.com/intridea/grape
gem 'grape', '~> 0.8.0'
gem 'grape-entity', '~> 0.4.3'

# Pagination
gem "kaminari", "~> 0.15.1"

# Use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.1.2'

# Use unicorn as the app server
# gem 'unicorn'

# assets management
gem "bower"

# styling
gem 'sass-rails', '~> 5.0'
gem 'sprockets', '2.11.0' # 2.12.0 is broken
gem 'compass-rails', '~> 2.0.4'
gem 'bootstrap-sass'
gem "font-awesome-rails"
gem 'susy'

# scripting
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'

# See https://github.com/sstephenson/execjs#readme for more supported runtimes
# gem 'therubyracer',  platforms: :ruby

# Kairos settings
gem 'settingslogic'

group :development do
  # debugging
  gem 'pry',                     require:false
  gem 'pry-nav',                 require:false
  gem 'pry-doc',                 require:false
  gem 'pry-rails'
  gem 'ruby-prof',               require:false

  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring',                  require: false

  # content generation
  gem 'lipsum'

  # internationalization
  gem 'i18n-tasks'

  # documentation
  gem 'sdoc'
  gem 'yard'
  gem 'rails-erd'
  gem 'railroady'

  # automation
  # gem 'capistrano'
end

group :development, :test do
  # tdd
  gem 'rspec',                   require:false
  gem 'rspec-rails',             require:false
  gem 'factory_girl_rails',      require:false  # replace fixtures
  gem 'faker',                   require:false  # generating fake data such as names, addresses, and phone numbers

  # gem 'debugger'
  gem 'html2haml'
end
