server:
  build: ..
  volumes:
    - ..:/kairos
    - ../db/backup:/kairos/db/backup
  ports:
    - "3001:3000"
  environment:
    RAILS_ENV: development
  command: bin/rails server --port 3000 --binding 0.0.0.0
